# -*- coding: utf-8 -*-
"""train_movie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ir8712J7vDyTG_qtgzk97cDxAXkaPAJp
"""

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

df = pd.read_csv("/content/movie_metadata.csv")
df.head()

df.info()

df.describe()

df.info()

df = df[
    [
        "budget",
        "gross",
        "duration",
        "genres",
        "imdb_score",
        "num_voted_users"
    ]
]

df = df.dropna()

df.isnull().sum()

# Remove invalid values
df = df[(df["budget"] > 0) & (df["gross"] > 0)]

# Create Target
df["target"] = np.where(df["gross"] >= df["budget"], 1, 0)

df["genres"] = df["genres"].apply(lambda x: x.split("|")[0])

# Encode Genre
encoder = LabelEncoder()
df["genres"] = encoder.fit_transform(df["genres"])
joblib.dump(encoder, "genre_encoder.pkl")

x = df.drop(["gross", "target"], axis=1)
y = df["target"]

#Scaler

scaler = StandardScaler()
x = scaler.fit_transform(x)
joblib.dump(scaler, "scaler.pkl")

# Train Test Split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

# Build ANN Model
# ===========================

model = Sequential()

model.add(Dense(32, activation="relu", input_shape=(x_train.shape[1],)))
model.add(Dense(16, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

# Compile Model
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Train Model

model.fit(x_train,y_train,epochs=20,batch_size=32,validation_split=0.2)

# Evaluate Model

loss, accuracy = model.evaluate(x_test, y_test)
print("Test Accuracy:", accuracy)

model.save("movie_success_ann.keras")

print("Model Saved Successfully!")